<?php

declare(strict_types=1);

namespace DedalusSDK\Chat\Completions\ChatCompletionAssistantMessageParam;

use DedalusSDK\Core\Attributes\Required;
use DedalusSDK\Core\Concerns\SdkModel;
use DedalusSDK\Core\Contracts\BaseModel;

/**
 * Deprecated and replaced by `tool_calls`. The name and arguments of a function that should be called, as generated by the model.
 *
 * Fields:
 * - arguments (required): str
 * - name (required): str
 *
 * @phpstan-type FunctionCallShape = array{arguments: string, name: string}
 */
final class FunctionCall implements BaseModel
{
    /** @use SdkModel<FunctionCallShape> */
    use SdkModel;

    /**
     * The arguments to call the function with, as generated by the model in JSON format. Note that the model does not always generate valid JSON, and may hallucinate parameters not defined by your function schema. Validate the arguments in your code before calling your function.
     */
    #[Required]
    public string $arguments;

    /**
     * The name of the function to call.
     */
    #[Required]
    public string $name;

    /**
     * `new FunctionCall()` is missing required properties by the API.
     *
     * To enforce required parameters use
     * ```
     * FunctionCall::with(arguments: ..., name: ...)
     * ```
     *
     * Otherwise ensure the following setters are called
     *
     * ```
     * (new FunctionCall)->withArguments(...)->withName(...)
     * ```
     */
    public function __construct()
    {
        $this->initialize();
    }

    /**
     * Construct an instance from the required parameters.
     *
     * You must use named parameters to construct any parameters with a default value.
     */
    public static function with(string $arguments, string $name): self
    {
        $self = new self;

        $self['arguments'] = $arguments;
        $self['name'] = $name;

        return $self;
    }

    /**
     * The arguments to call the function with, as generated by the model in JSON format. Note that the model does not always generate valid JSON, and may hallucinate parameters not defined by your function schema. Validate the arguments in your code before calling your function.
     */
    public function withArguments(string $arguments): self
    {
        $self = clone $this;
        $self['arguments'] = $arguments;

        return $self;
    }

    /**
     * The name of the function to call.
     */
    public function withName(string $name): self
    {
        $self = clone $this;
        $self['name'] = $name;

        return $self;
    }
}
