<?php

declare(strict_types=1);

namespace DedalusSDK\Services;

use DedalusSDK\Client;
use DedalusSDK\Core\Exceptions\APIException;
use DedalusSDK\Core\FileParam;
use DedalusSDK\Core\Util;
use DedalusSDK\Images\ImageGenerateParams\Background;
use DedalusSDK\Images\ImageGenerateParams\Moderation;
use DedalusSDK\Images\ImageGenerateParams\OutputFormat;
use DedalusSDK\Images\ImageGenerateParams\Quality;
use DedalusSDK\Images\ImageGenerateParams\ResponseFormat;
use DedalusSDK\Images\ImageGenerateParams\Size;
use DedalusSDK\Images\ImageGenerateParams\Style;
use DedalusSDK\Images\ImagesResponse;
use DedalusSDK\RequestOptions;
use DedalusSDK\ServiceContracts\ImagesContract;

/**
 * @phpstan-import-type RequestOpts from \DedalusSDK\RequestOptions
 */
final class ImagesService implements ImagesContract
{
    /**
     * @api
     */
    public ImagesRawService $raw;

    /**
     * @internal
     */
    public function __construct(private Client $client)
    {
        $this->raw = new ImagesRawService($client);
    }

    /**
     * @api
     *
     * Create variations of an image.
     *
     * DALL·E 2 only. Upload an image to generate variations.
     *
     * @param RequestOpts|null $requestOptions
     *
     * @throws APIException
     */
    public function createVariation(
        string|FileParam $image,
        ?string $model = 'openai/dall-e-2',
        ?int $n = 1,
        ?string $responseFormat = 'url',
        ?string $size = '1024x1024',
        ?string $user = null,
        RequestOptions|array|null $requestOptions = null,
    ): ImagesResponse {
        $params = Util::removeNulls(
            [
                'image' => $image,
                'model' => $model,
                'n' => $n,
                'responseFormat' => $responseFormat,
                'size' => $size,
                'user' => $user,
            ],
        );

        // @phpstan-ignore-next-line argument.type
        $response = $this->raw->createVariation(params: $params, requestOptions: $requestOptions);

        return $response->parse();
    }

    /**
     * @api
     *
     * Edit images using inpainting.
     *
     * Supports dall-e-2 and gpt-image-1. Upload an image and optionally a mask
     * to indicate which areas to regenerate based on the prompt.
     *
     * @param RequestOpts|null $requestOptions
     *
     * @throws APIException
     */
    public function edit(
        string|FileParam $image,
        string $prompt,
        string|FileParam|null $mask = null,
        ?string $model = 'openai/dall-e-2',
        ?int $n = 1,
        ?string $responseFormat = 'url',
        ?string $size = '1024x1024',
        ?string $user = null,
        RequestOptions|array|null $requestOptions = null,
    ): ImagesResponse {
        $params = Util::removeNulls(
            [
                'image' => $image,
                'prompt' => $prompt,
                'mask' => $mask,
                'model' => $model,
                'n' => $n,
                'responseFormat' => $responseFormat,
                'size' => $size,
                'user' => $user,
            ],
        );

        // @phpstan-ignore-next-line argument.type
        $response = $this->raw->edit(params: $params, requestOptions: $requestOptions);

        return $response->parse();
    }

    /**
     * @api
     *
     * Generate images from text prompts.
     *
     * Pure image generation models only (DALL-E, GPT Image).
     * For multimodal models like gemini-2.5-flash-image, use /v1/chat/completions.
     *
     * @param string $prompt A text description of the desired image(s). The maximum length is 32000 characters for `gpt-image-1`, 1000 characters for `dall-e-2` and 4000 characters for `dall-e-3`.
     * @param Background|value-of<Background>|null $background Allows to set transparency for the background of the generated image(s).
     * This parameter is only supported for `gpt-image-1`. Must be one of
     * `transparent`, `opaque` or `auto` (default value). When `auto` is used, the
     * model will automatically determine the best background for the image.
     *
     * If `transparent`, the output format needs to support transparency, so it
     * should be set to either `png` (default value) or `webp`.
     * @param string|null $model The model to use for image generation. One of `openai/dall-e-2`, `openai/dall-e-3`, or `openai/gpt-image-1`. Defaults to `openai/dall-e-2` unless a parameter specific to `gpt-image-1` is used.
     * @param Moderation|value-of<Moderation>|null $moderation Control the content-moderation level for images generated by `gpt-image-1`. Must be either `low` for less restrictive filtering or `auto` (default value).
     * @param int|null $n The number of images to generate. Must be between 1 and 10. For `dall-e-3`, only `n=1` is supported.
     * @param int|null $outputCompression The compression level (0-100%) for the generated images. This parameter is only supported for `gpt-image-1` with the `webp` or `jpeg` output formats, and defaults to 100.
     * @param OutputFormat|value-of<OutputFormat>|null $outputFormat The format in which the generated images are returned. This parameter is only supported for `gpt-image-1`. Must be one of `png`, `jpeg`, or `webp`.
     * @param int|null $partialImages The number of partial images to generate. This parameter is used for
     * streaming responses that return partial images. Value must be between 0 and 3.
     * When set to 0, the response will be a single image sent in one streaming event.
     *
     * Note that the final image may be sent before the full number of partial images
     * are generated if the full image is generated more quickly.
     * @param Quality|value-of<Quality>|null $quality The quality of the image that will be generated.
     *
     * - `auto` (default value) will automatically select the best quality for the given model.
     * - `high`, `medium` and `low` are supported for `gpt-image-1`.
     * - `hd` and `standard` are supported for `dall-e-3`.
     * - `standard` is the only option for `dall-e-2`.
     * @param ResponseFormat|value-of<ResponseFormat>|null $responseFormat The format in which generated images with `dall-e-2` and `dall-e-3` are returned. Must be one of `url` or `b64_json`. URLs are only valid for 60 minutes after the image has been generated. This parameter isn't supported for `gpt-image-1` which will always return base64-encoded images.
     * @param Size|value-of<Size>|null $size The size of the generated images. Must be one of `1024x1024`, `1536x1024` (landscape), `1024x1536` (portrait), or `auto` (default value) for `gpt-image-1`, one of `256x256`, `512x512`, or `1024x1024` for `dall-e-2`, and one of `1024x1024`, `1792x1024`, or `1024x1792` for `dall-e-3`.
     * @param bool|null $stream Generate the image in streaming mode. Defaults to `false`. See the
     * [Image generation guide](https://platform.openai.com/docs/guides/image-generation) for more information.
     * This parameter is only supported for `gpt-image-1`.
     * @param Style|value-of<Style>|null $style The style of the generated images. This parameter is only supported for `dall-e-3`. Must be one of `vivid` or `natural`. Vivid causes the model to lean towards generating hyper-real and dramatic images. Natural causes the model to produce more natural, less hyper-real looking images.
     * @param string|null $user A unique identifier representing your end-user, which can help OpenAI to monitor and detect abuse. [Learn more](https://platform.openai.com/docs/guides/safety-best-practices#end-user-ids).
     * @param RequestOpts|null $requestOptions
     *
     * @throws APIException
     */
    public function generate(
        string $prompt,
        Background|string|null $background = null,
        ?string $model = null,
        Moderation|string|null $moderation = null,
        ?int $n = null,
        ?int $outputCompression = null,
        OutputFormat|string|null $outputFormat = null,
        ?int $partialImages = null,
        Quality|string|null $quality = null,
        ResponseFormat|string|null $responseFormat = null,
        Size|string|null $size = null,
        ?bool $stream = null,
        Style|string|null $style = null,
        ?string $user = null,
        RequestOptions|array|null $requestOptions = null,
    ): ImagesResponse {
        $params = Util::removeNulls(
            [
                'prompt' => $prompt,
                'background' => $background,
                'model' => $model,
                'moderation' => $moderation,
                'n' => $n,
                'outputCompression' => $outputCompression,
                'outputFormat' => $outputFormat,
                'partialImages' => $partialImages,
                'quality' => $quality,
                'responseFormat' => $responseFormat,
                'size' => $size,
                'stream' => $stream,
                'style' => $style,
                'user' => $user,
            ],
        );

        // @phpstan-ignore-next-line argument.type
        $response = $this->raw->generate(params: $params, requestOptions: $requestOptions);

        return $response->parse();
    }
}
