<?php

declare(strict_types=1);

namespace DedalusSDK\Chat\Completions\ChatCompletionMessageCustomToolCall;

use DedalusSDK\Core\Attributes\Required;
use DedalusSDK\Core\Concerns\SdkModel;
use DedalusSDK\Core\Contracts\BaseModel;

/**
 * The custom tool that the model called.
 *
 * Fields:
 * - name (required): str
 * - input (required): str
 *
 * @phpstan-type CustomShape = array{input: string, name: string}
 */
final class Custom implements BaseModel
{
    /** @use SdkModel<CustomShape> */
    use SdkModel;

    /**
     * The input for the custom tool call generated by the model.
     */
    #[Required]
    public string $input;

    /**
     * The name of the custom tool to call.
     */
    #[Required]
    public string $name;

    /**
     * `new Custom()` is missing required properties by the API.
     *
     * To enforce required parameters use
     * ```
     * Custom::with(input: ..., name: ...)
     * ```
     *
     * Otherwise ensure the following setters are called
     *
     * ```
     * (new Custom)->withInput(...)->withName(...)
     * ```
     */
    public function __construct()
    {
        $this->initialize();
    }

    /**
     * Construct an instance from the required parameters.
     *
     * You must use named parameters to construct any parameters with a default value.
     */
    public static function with(string $input, string $name): self
    {
        $self = new self;

        $self['input'] = $input;
        $self['name'] = $name;

        return $self;
    }

    /**
     * The input for the custom tool call generated by the model.
     */
    public function withInput(string $input): self
    {
        $self = clone $this;
        $self['input'] = $input;

        return $self;
    }

    /**
     * The name of the custom tool to call.
     */
    public function withName(string $name): self
    {
        $self = clone $this;
        $self['name'] = $name;

        return $self;
    }
}
