<?php

declare(strict_types=1);

namespace DedalusSDK\Responses;

use DedalusSDK\Core\Attributes\Optional;
use DedalusSDK\Core\Attributes\Required;
use DedalusSDK\Core\Concerns\SdkModel;
use DedalusSDK\Core\Contracts\BaseModel;
use DedalusSDK\Core\Conversion\MapOf;
use DedalusSDK\JSONValueInput;
use DedalusSDK\MCPToolResult;
use DedalusSDK\Responses\Response\Instructions;
use DedalusSDK\Responses\Response\MCPServerError;
use DedalusSDK\Responses\Response\Object_;
use DedalusSDK\Responses\Response\Status;
use DedalusSDK\Responses\Response\ToolChoice;

/**
 * Responses API response with Dedalus extensions.
 *
 * @phpstan-import-type InstructionsVariants from \DedalusSDK\Responses\Response\Instructions
 * @phpstan-import-type ToolChoiceVariants from \DedalusSDK\Responses\Response\ToolChoice
 * @phpstan-import-type InstructionsShape from \DedalusSDK\Responses\Response\Instructions
 * @phpstan-import-type MCPServerErrorShape from \DedalusSDK\Responses\Response\MCPServerError
 * @phpstan-import-type ToolChoiceShape from \DedalusSDK\Responses\Response\ToolChoice
 *
 * @phpstan-type ResponseShape = array{
 *   id: string,
 *   createdAt: float,
 *   model: string,
 *   output: list<mixed>,
 *   status: Status|value-of<Status>,
 *   background?: bool|null,
 *   completedAt?: float|null,
 *   conversation?: array<string,mixed>|null,
 *   error?: array<string,mixed>|null,
 *   frequencyPenalty?: float|null,
 *   incompleteDetails?: array<string,string>|null,
 *   instructions?: InstructionsShape|null,
 *   maxOutputTokens?: int|null,
 *   maxToolCalls?: int|null,
 *   mcpServerErrors?: array<string,MCPServerError|MCPServerErrorShape>|null,
 *   mcpToolResults?: list<mixed>|null,
 *   metadata?: array<string,string>|null,
 *   object?: null|Object_|value-of<Object_>,
 *   outputText?: string|null,
 *   parallelToolCalls?: bool|null,
 *   presencePenalty?: float|null,
 *   previousResponseID?: string|null,
 *   promptCacheKey?: string|null,
 *   reasoning?: array<string,mixed>|null,
 *   safetyIdentifier?: string|null,
 *   serviceTier?: string|null,
 *   store?: bool|null,
 *   temperature?: float|null,
 *   text?: array<string,mixed>|null,
 *   toolChoice?: ToolChoiceShape|null,
 *   tools?: list<mixed>|null,
 *   toolsExecuted?: list<string>|null,
 *   topLogprobs?: int|null,
 *   topP?: float|null,
 *   truncation?: string|null,
 *   usage?: array<string,mixed>|null,
 * }
 */
final class Response implements BaseModel
{
    /** @use SdkModel<ResponseShape> */
    use SdkModel;

    /**
     * Unique identifier for this Response.
     */
    #[Required]
    public string $id;

    /**
     * Unix timestamp (in seconds) when this Response was created.
     */
    #[Required('created_at')]
    public float $createdAt;

    /**
     * The model used for this response.
     */
    #[Required]
    public string $model;

    /**
     * Array of content items generated by the model.
     *
     * @var list<mixed> $output
     */
    #[Required(list: new MapOf(JSONValueInput::class, nullable: true))]
    public array $output;

    /**
     * The status of the response generation.
     *
     * @var value-of<Status> $status
     */
    #[Required(enum: Status::class)]
    public string $status;

    /**
     * Whether the request was run in the background.
     */
    #[Optional(nullable: true)]
    public ?bool $background;

    /**
     * Unix timestamp (in seconds) when the response was completed.
     */
    #[Optional('completed_at', nullable: true)]
    public ?float $completedAt;

    /**
     * Conversation this response belongs to (requires BYOK).
     *
     * @var array<string,mixed>|null $conversation
     */
    #[Optional(
        type: new MapOf(JSONValueInput::class, nullable: true),
        nullable: true
    )]
    public ?array $conversation;

    /**
     * Error details if status is 'failed'.
     *
     * @var array<string,mixed>|null $error
     */
    #[Optional(
        type: new MapOf(JSONValueInput::class, nullable: true),
        nullable: true
    )]
    public ?array $error;

    /**
     * Frequency penalty used for this response.
     */
    #[Optional('frequency_penalty', nullable: true)]
    public ?float $frequencyPenalty;

    /**
     * Details about why the response is incomplete (e.g., max_output_tokens, content_filter).
     *
     * @var array<string,string>|null $incompleteDetails
     */
    #[Optional('incomplete_details', map: 'string', nullable: true)]
    public ?array $incompleteDetails;

    /**
     * System/developer instructions used.
     *
     * @var InstructionsVariants|null $instructions
     */
    #[Optional(union: Instructions::class, nullable: true)]
    public string|array|null $instructions;

    /**
     * Maximum output tokens allowed for this response.
     */
    #[Optional('max_output_tokens', nullable: true)]
    public ?int $maxOutputTokens;

    /**
     * Maximum tool calls allowed for this response.
     */
    #[Optional('max_tool_calls', nullable: true)]
    public ?int $maxToolCalls;

    /**
     * MCP server failures keyed by server name.
     *
     * @var array<string,MCPServerError>|null $mcpServerErrors
     */
    #[Optional('mcp_server_errors', map: MCPServerError::class, nullable: true)]
    public ?array $mcpServerErrors;

    /**
     * Results of MCP tool executions including inputs, outputs, and timing.
     *
     * @var list<mixed>|null $mcpToolResults
     */
    #[Optional('mcp_tool_results', list: MCPToolResult::class, nullable: true)]
    public ?array $mcpToolResults;

    /**
     * Key-value pairs attached to this response (requires BYOK).
     *
     * @var array<string,string>|null $metadata
     */
    #[Optional(map: 'string', nullable: true)]
    public ?array $metadata;

    /**
     * The object type, always 'response'.
     *
     * @var value-of<Object_>|null $object
     */
    #[Optional(enum: Object_::class)]
    public ?string $object;

    /**
     * Aggregated text output from all output_text items (SDK-only convenience property).
     */
    #[Optional('output_text', nullable: true)]
    public ?string $outputText;

    /**
     * Whether parallel tool calls were enabled.
     */
    #[Optional('parallel_tool_calls', nullable: true)]
    public ?bool $parallelToolCalls;

    /**
     * Presence penalty used for this response.
     */
    #[Optional('presence_penalty', nullable: true)]
    public ?float $presencePenalty;

    /**
     * Previous response ID referenced, if any.
     */
    #[Optional('previous_response_id', nullable: true)]
    public ?string $previousResponseID;

    /**
     * Prompt cache key used for this response.
     */
    #[Optional('prompt_cache_key', nullable: true)]
    public ?string $promptCacheKey;

    /**
     * Reasoning configuration and outputs.
     *
     * @var array<string,mixed>|null $reasoning
     */
    #[Optional(
        type: new MapOf(JSONValueInput::class, nullable: true),
        nullable: true
    )]
    public ?array $reasoning;

    /**
     * Safety identifier used for this response.
     */
    #[Optional('safety_identifier', nullable: true)]
    public ?string $safetyIdentifier;

    /**
     * Service tier used for this response.
     */
    #[Optional('service_tier', nullable: true)]
    public ?string $serviceTier;

    /**
     * Whether the response was stored for later retrieval.
     */
    #[Optional(nullable: true)]
    public ?bool $store;

    /**
     * Temperature parameter used.
     */
    #[Optional(nullable: true)]
    public ?float $temperature;

    /**
     * Text configuration used for this response.
     *
     * @var array<string,mixed>|null $text
     */
    #[Optional(
        type: new MapOf(JSONValueInput::class, nullable: true),
        nullable: true
    )]
    public ?array $text;

    /**
     * Tool choice configuration used.
     *
     * @var ToolChoiceVariants|null $toolChoice
     */
    #[Optional('tool_choice', union: ToolChoice::class, nullable: true)]
    public string|array|null $toolChoice;

    /**
     * Tools that were available to the model.
     *
     * @var list<mixed>|null $tools
     */
    #[Optional(
        list: new MapOf(JSONValueInput::class, nullable: true),
        nullable: true
    )]
    public ?array $tools;

    /**
     * List of tool names that were executed server-side (e.g., MCP tools).
     *
     * @var list<string>|null $toolsExecuted
     */
    #[Optional('tools_executed', list: 'string', nullable: true)]
    public ?array $toolsExecuted;

    /**
     * Number of logprob tokens returned per position.
     */
    #[Optional('top_logprobs', nullable: true)]
    public ?int $topLogprobs;

    /**
     * Top-p parameter used.
     */
    #[Optional('top_p', nullable: true)]
    public ?float $topP;

    /**
     * Truncation strategy applied when context exceeded limits.
     */
    #[Optional(nullable: true)]
    public ?string $truncation;

    /**
     * Token usage statistics for the response.
     *
     * @var array<string,mixed>|null $usage
     */
    #[Optional(
        type: new MapOf(JSONValueInput::class, nullable: true),
        nullable: true
    )]
    public ?array $usage;

    /**
     * `new Response()` is missing required properties by the API.
     *
     * To enforce required parameters use
     * ```
     * Response::with(id: ..., createdAt: ..., model: ..., output: ..., status: ...)
     * ```
     *
     * Otherwise ensure the following setters are called
     *
     * ```
     * (new Response)
     *   ->withID(...)
     *   ->withCreatedAt(...)
     *   ->withModel(...)
     *   ->withOutput(...)
     *   ->withStatus(...)
     * ```
     */
    public function __construct()
    {
        $this->initialize();
    }

    /**
     * Construct an instance from the required parameters.
     *
     * You must use named parameters to construct any parameters with a default value.
     *
     * @param list<mixed> $output
     * @param Status|value-of<Status> $status
     * @param array<string,mixed>|null $conversation
     * @param array<string,mixed>|null $error
     * @param array<string,string>|null $incompleteDetails
     * @param InstructionsShape|null $instructions
     * @param array<string,MCPServerError|MCPServerErrorShape>|null $mcpServerErrors
     * @param list<mixed>|null $mcpToolResults
     * @param array<string,string>|null $metadata
     * @param Object_|value-of<Object_>|null $object
     * @param array<string,mixed>|null $reasoning
     * @param array<string,mixed>|null $text
     * @param ToolChoiceShape|null $toolChoice
     * @param list<mixed>|null $tools
     * @param list<string>|null $toolsExecuted
     * @param array<string,mixed>|null $usage
     */
    public static function with(
        string $id,
        float $createdAt,
        string $model,
        array $output,
        Status|string $status,
        ?bool $background = null,
        ?float $completedAt = null,
        ?array $conversation = null,
        ?array $error = null,
        ?float $frequencyPenalty = null,
        ?array $incompleteDetails = null,
        string|array|null $instructions = null,
        ?int $maxOutputTokens = null,
        ?int $maxToolCalls = null,
        ?array $mcpServerErrors = null,
        ?array $mcpToolResults = null,
        ?array $metadata = null,
        Object_|string|null $object = null,
        ?string $outputText = null,
        ?bool $parallelToolCalls = null,
        ?float $presencePenalty = null,
        ?string $previousResponseID = null,
        ?string $promptCacheKey = null,
        ?array $reasoning = null,
        ?string $safetyIdentifier = null,
        ?string $serviceTier = null,
        ?bool $store = null,
        ?float $temperature = null,
        ?array $text = null,
        string|array|null $toolChoice = null,
        ?array $tools = null,
        ?array $toolsExecuted = null,
        ?int $topLogprobs = null,
        ?float $topP = null,
        ?string $truncation = null,
        ?array $usage = null,
    ): self {
        $self = new self;

        $self['id'] = $id;
        $self['createdAt'] = $createdAt;
        $self['model'] = $model;
        $self['output'] = $output;
        $self['status'] = $status;

        null !== $background && $self['background'] = $background;
        null !== $completedAt && $self['completedAt'] = $completedAt;
        null !== $conversation && $self['conversation'] = $conversation;
        null !== $error && $self['error'] = $error;
        null !== $frequencyPenalty && $self['frequencyPenalty'] = $frequencyPenalty;
        null !== $incompleteDetails && $self['incompleteDetails'] = $incompleteDetails;
        null !== $instructions && $self['instructions'] = $instructions;
        null !== $maxOutputTokens && $self['maxOutputTokens'] = $maxOutputTokens;
        null !== $maxToolCalls && $self['maxToolCalls'] = $maxToolCalls;
        null !== $mcpServerErrors && $self['mcpServerErrors'] = $mcpServerErrors;
        null !== $mcpToolResults && $self['mcpToolResults'] = $mcpToolResults;
        null !== $metadata && $self['metadata'] = $metadata;
        null !== $object && $self['object'] = $object;
        null !== $outputText && $self['outputText'] = $outputText;
        null !== $parallelToolCalls && $self['parallelToolCalls'] = $parallelToolCalls;
        null !== $presencePenalty && $self['presencePenalty'] = $presencePenalty;
        null !== $previousResponseID && $self['previousResponseID'] = $previousResponseID;
        null !== $promptCacheKey && $self['promptCacheKey'] = $promptCacheKey;
        null !== $reasoning && $self['reasoning'] = $reasoning;
        null !== $safetyIdentifier && $self['safetyIdentifier'] = $safetyIdentifier;
        null !== $serviceTier && $self['serviceTier'] = $serviceTier;
        null !== $store && $self['store'] = $store;
        null !== $temperature && $self['temperature'] = $temperature;
        null !== $text && $self['text'] = $text;
        null !== $toolChoice && $self['toolChoice'] = $toolChoice;
        null !== $tools && $self['tools'] = $tools;
        null !== $toolsExecuted && $self['toolsExecuted'] = $toolsExecuted;
        null !== $topLogprobs && $self['topLogprobs'] = $topLogprobs;
        null !== $topP && $self['topP'] = $topP;
        null !== $truncation && $self['truncation'] = $truncation;
        null !== $usage && $self['usage'] = $usage;

        return $self;
    }

    /**
     * Unique identifier for this Response.
     */
    public function withID(string $id): self
    {
        $self = clone $this;
        $self['id'] = $id;

        return $self;
    }

    /**
     * Unix timestamp (in seconds) when this Response was created.
     */
    public function withCreatedAt(float $createdAt): self
    {
        $self = clone $this;
        $self['createdAt'] = $createdAt;

        return $self;
    }

    /**
     * The model used for this response.
     */
    public function withModel(string $model): self
    {
        $self = clone $this;
        $self['model'] = $model;

        return $self;
    }

    /**
     * Array of content items generated by the model.
     *
     * @param list<mixed> $output
     */
    public function withOutput(array $output): self
    {
        $self = clone $this;
        $self['output'] = $output;

        return $self;
    }

    /**
     * The status of the response generation.
     *
     * @param Status|value-of<Status> $status
     */
    public function withStatus(Status|string $status): self
    {
        $self = clone $this;
        $self['status'] = $status;

        return $self;
    }

    /**
     * Whether the request was run in the background.
     */
    public function withBackground(?bool $background): self
    {
        $self = clone $this;
        $self['background'] = $background;

        return $self;
    }

    /**
     * Unix timestamp (in seconds) when the response was completed.
     */
    public function withCompletedAt(?float $completedAt): self
    {
        $self = clone $this;
        $self['completedAt'] = $completedAt;

        return $self;
    }

    /**
     * Conversation this response belongs to (requires BYOK).
     *
     * @param array<string,mixed>|null $conversation
     */
    public function withConversation(?array $conversation): self
    {
        $self = clone $this;
        $self['conversation'] = $conversation;

        return $self;
    }

    /**
     * Error details if status is 'failed'.
     *
     * @param array<string,mixed>|null $error
     */
    public function withError(?array $error): self
    {
        $self = clone $this;
        $self['error'] = $error;

        return $self;
    }

    /**
     * Frequency penalty used for this response.
     */
    public function withFrequencyPenalty(?float $frequencyPenalty): self
    {
        $self = clone $this;
        $self['frequencyPenalty'] = $frequencyPenalty;

        return $self;
    }

    /**
     * Details about why the response is incomplete (e.g., max_output_tokens, content_filter).
     *
     * @param array<string,string>|null $incompleteDetails
     */
    public function withIncompleteDetails(?array $incompleteDetails): self
    {
        $self = clone $this;
        $self['incompleteDetails'] = $incompleteDetails;

        return $self;
    }

    /**
     * System/developer instructions used.
     *
     * @param InstructionsShape|null $instructions
     */
    public function withInstructions(string|array|null $instructions): self
    {
        $self = clone $this;
        $self['instructions'] = $instructions;

        return $self;
    }

    /**
     * Maximum output tokens allowed for this response.
     */
    public function withMaxOutputTokens(?int $maxOutputTokens): self
    {
        $self = clone $this;
        $self['maxOutputTokens'] = $maxOutputTokens;

        return $self;
    }

    /**
     * Maximum tool calls allowed for this response.
     */
    public function withMaxToolCalls(?int $maxToolCalls): self
    {
        $self = clone $this;
        $self['maxToolCalls'] = $maxToolCalls;

        return $self;
    }

    /**
     * MCP server failures keyed by server name.
     *
     * @param array<string,MCPServerError|MCPServerErrorShape>|null $mcpServerErrors
     */
    public function withMCPServerErrors(?array $mcpServerErrors): self
    {
        $self = clone $this;
        $self['mcpServerErrors'] = $mcpServerErrors;

        return $self;
    }

    /**
     * Results of MCP tool executions including inputs, outputs, and timing.
     *
     * @param list<mixed>|null $mcpToolResults
     */
    public function withMCPToolResults(?array $mcpToolResults): self
    {
        $self = clone $this;
        $self['mcpToolResults'] = $mcpToolResults;

        return $self;
    }

    /**
     * Key-value pairs attached to this response (requires BYOK).
     *
     * @param array<string,string>|null $metadata
     */
    public function withMetadata(?array $metadata): self
    {
        $self = clone $this;
        $self['metadata'] = $metadata;

        return $self;
    }

    /**
     * The object type, always 'response'.
     *
     * @param Object_|value-of<Object_> $object
     */
    public function withObject(Object_|string $object): self
    {
        $self = clone $this;
        $self['object'] = $object;

        return $self;
    }

    /**
     * Aggregated text output from all output_text items (SDK-only convenience property).
     */
    public function withOutputText(?string $outputText): self
    {
        $self = clone $this;
        $self['outputText'] = $outputText;

        return $self;
    }

    /**
     * Whether parallel tool calls were enabled.
     */
    public function withParallelToolCalls(?bool $parallelToolCalls): self
    {
        $self = clone $this;
        $self['parallelToolCalls'] = $parallelToolCalls;

        return $self;
    }

    /**
     * Presence penalty used for this response.
     */
    public function withPresencePenalty(?float $presencePenalty): self
    {
        $self = clone $this;
        $self['presencePenalty'] = $presencePenalty;

        return $self;
    }

    /**
     * Previous response ID referenced, if any.
     */
    public function withPreviousResponseID(?string $previousResponseID): self
    {
        $self = clone $this;
        $self['previousResponseID'] = $previousResponseID;

        return $self;
    }

    /**
     * Prompt cache key used for this response.
     */
    public function withPromptCacheKey(?string $promptCacheKey): self
    {
        $self = clone $this;
        $self['promptCacheKey'] = $promptCacheKey;

        return $self;
    }

    /**
     * Reasoning configuration and outputs.
     *
     * @param array<string,mixed>|null $reasoning
     */
    public function withReasoning(?array $reasoning): self
    {
        $self = clone $this;
        $self['reasoning'] = $reasoning;

        return $self;
    }

    /**
     * Safety identifier used for this response.
     */
    public function withSafetyIdentifier(?string $safetyIdentifier): self
    {
        $self = clone $this;
        $self['safetyIdentifier'] = $safetyIdentifier;

        return $self;
    }

    /**
     * Service tier used for this response.
     */
    public function withServiceTier(?string $serviceTier): self
    {
        $self = clone $this;
        $self['serviceTier'] = $serviceTier;

        return $self;
    }

    /**
     * Whether the response was stored for later retrieval.
     */
    public function withStore(?bool $store): self
    {
        $self = clone $this;
        $self['store'] = $store;

        return $self;
    }

    /**
     * Temperature parameter used.
     */
    public function withTemperature(?float $temperature): self
    {
        $self = clone $this;
        $self['temperature'] = $temperature;

        return $self;
    }

    /**
     * Text configuration used for this response.
     *
     * @param array<string,mixed>|null $text
     */
    public function withText(?array $text): self
    {
        $self = clone $this;
        $self['text'] = $text;

        return $self;
    }

    /**
     * Tool choice configuration used.
     *
     * @param ToolChoiceShape|null $toolChoice
     */
    public function withToolChoice(string|array|null $toolChoice): self
    {
        $self = clone $this;
        $self['toolChoice'] = $toolChoice;

        return $self;
    }

    /**
     * Tools that were available to the model.
     *
     * @param list<mixed>|null $tools
     */
    public function withTools(?array $tools): self
    {
        $self = clone $this;
        $self['tools'] = $tools;

        return $self;
    }

    /**
     * List of tool names that were executed server-side (e.g., MCP tools).
     *
     * @param list<string>|null $toolsExecuted
     */
    public function withToolsExecuted(?array $toolsExecuted): self
    {
        $self = clone $this;
        $self['toolsExecuted'] = $toolsExecuted;

        return $self;
    }

    /**
     * Number of logprob tokens returned per position.
     */
    public function withTopLogprobs(?int $topLogprobs): self
    {
        $self = clone $this;
        $self['topLogprobs'] = $topLogprobs;

        return $self;
    }

    /**
     * Top-p parameter used.
     */
    public function withTopP(?float $topP): self
    {
        $self = clone $this;
        $self['topP'] = $topP;

        return $self;
    }

    /**
     * Truncation strategy applied when context exceeded limits.
     */
    public function withTruncation(?string $truncation): self
    {
        $self = clone $this;
        $self['truncation'] = $truncation;

        return $self;
    }

    /**
     * Token usage statistics for the response.
     *
     * @param array<string,mixed>|null $usage
     */
    public function withUsage(?array $usage): self
    {
        $self = clone $this;
        $self['usage'] = $usage;

        return $self;
    }
}
