<?php

declare(strict_types=1);

namespace DedalusSDK\Embeddings;

use DedalusSDK\Core\Attributes\Required;
use DedalusSDK\Core\Concerns\SdkModel;
use DedalusSDK\Core\Contracts\BaseModel;
use DedalusSDK\Embeddings\CreateEmbeddingResponse\Data;
use DedalusSDK\Embeddings\CreateEmbeddingResponse\Usage;

/**
 * Schema for EmbeddingResponse.
 *
 * Fields:
 * - data (required): list[Embedding]
 * - model (required): str
 * - object (required): Literal["list"]
 * - usage (required): Usage
 *
 * @phpstan-import-type DataShape from \DedalusSDK\Embeddings\CreateEmbeddingResponse\Data
 * @phpstan-import-type UsageShape from \DedalusSDK\Embeddings\CreateEmbeddingResponse\Usage
 *
 * @phpstan-type CreateEmbeddingResponseShape = array{
 *   data: list<Data|DataShape>,
 *   model: string,
 *   object: 'list',
 *   usage: Usage|UsageShape,
 * }
 */
final class CreateEmbeddingResponse implements BaseModel
{
    /** @use SdkModel<CreateEmbeddingResponseShape> */
    use SdkModel;

    /**
     * The object type, which is always "list".
     *
     * @var 'list' $object
     */
    #[Required]
    public string $object = 'list';

    /**
     * The list of embeddings generated by the model.
     *
     * @var list<Data> $data
     */
    #[Required(list: Data::class)]
    public array $data;

    /**
     * The name of the model used to generate the embedding.
     */
    #[Required]
    public string $model;

    /**
     * The usage information for the request.
     */
    #[Required]
    public Usage $usage;

    /**
     * `new CreateEmbeddingResponse()` is missing required properties by the API.
     *
     * To enforce required parameters use
     * ```
     * CreateEmbeddingResponse::with(data: ..., model: ..., usage: ...)
     * ```
     *
     * Otherwise ensure the following setters are called
     *
     * ```
     * (new CreateEmbeddingResponse)->withData(...)->withModel(...)->withUsage(...)
     * ```
     */
    public function __construct()
    {
        $this->initialize();
    }

    /**
     * Construct an instance from the required parameters.
     *
     * You must use named parameters to construct any parameters with a default value.
     *
     * @param list<Data|DataShape> $data
     * @param Usage|UsageShape $usage
     */
    public static function with(
        array $data,
        string $model,
        Usage|array $usage
    ): self {
        $self = new self;

        $self['data'] = $data;
        $self['model'] = $model;
        $self['usage'] = $usage;

        return $self;
    }

    /**
     * The list of embeddings generated by the model.
     *
     * @param list<Data|DataShape> $data
     */
    public function withData(array $data): self
    {
        $self = clone $this;
        $self['data'] = $data;

        return $self;
    }

    /**
     * The name of the model used to generate the embedding.
     */
    public function withModel(string $model): self
    {
        $self = clone $this;
        $self['model'] = $model;

        return $self;
    }

    /**
     * The object type, which is always "list".
     *
     * @param 'list' $object
     */
    public function withObject(string $object): self
    {
        $self = clone $this;
        $self['object'] = $object;

        return $self;
    }

    /**
     * The usage information for the request.
     *
     * @param Usage|UsageShape $usage
     */
    public function withUsage(Usage|array $usage): self
    {
        $self = clone $this;
        $self['usage'] = $usage;

        return $self;
    }
}
