<?php

declare(strict_types=1);

namespace DedalusSDK\Chat\Completions\ChoiceDeltaToolCall;

use DedalusSDK\Core\Attributes\Optional;
use DedalusSDK\Core\Concerns\SdkModel;
use DedalusSDK\Core\Contracts\BaseModel;

/**
 * Schema for ChatCompletionMessageToolCallChunkFunction.
 *
 * Fields:
 * - name (optional): str
 * - arguments (optional): str
 *
 * @phpstan-type FunctionShape = array{arguments?: string|null, name?: string|null}
 */
final class Function_ implements BaseModel
{
    /** @use SdkModel<FunctionShape> */
    use SdkModel;

    /**
     * The arguments to call the function with, as generated by the model in JSON format. Note that the model does not always generate valid JSON, and may hallucinate parameters not defined by your function schema. Validate the arguments in your code before calling your function.
     */
    #[Optional]
    public ?string $arguments;

    /**
     * The name of the function to call.
     */
    #[Optional]
    public ?string $name;

    public function __construct()
    {
        $this->initialize();
    }

    /**
     * Construct an instance from the required parameters.
     *
     * You must use named parameters to construct any parameters with a default value.
     */
    public static function with(
        ?string $arguments = null,
        ?string $name = null
    ): self {
        $self = new self;

        null !== $arguments && $self['arguments'] = $arguments;
        null !== $name && $self['name'] = $name;

        return $self;
    }

    /**
     * The arguments to call the function with, as generated by the model in JSON format. Note that the model does not always generate valid JSON, and may hallucinate parameters not defined by your function schema. Validate the arguments in your code before calling your function.
     */
    public function withArguments(string $arguments): self
    {
        $self = clone $this;
        $self['arguments'] = $arguments;

        return $self;
    }

    /**
     * The name of the function to call.
     */
    public function withName(string $name): self
    {
        $self = clone $this;
        $self['name'] = $name;

        return $self;
    }
}
