<?php

declare(strict_types=1);

namespace DedalusSDK\Images;

use DedalusSDK\Core\Attributes\Optional;
use DedalusSDK\Core\Attributes\Required;
use DedalusSDK\Core\Concerns\SdkModel;
use DedalusSDK\Core\Concerns\SdkParams;
use DedalusSDK\Core\Contracts\BaseModel;
use DedalusSDK\Images\ImageGenerateParams\Background;
use DedalusSDK\Images\ImageGenerateParams\Moderation;
use DedalusSDK\Images\ImageGenerateParams\OutputFormat;
use DedalusSDK\Images\ImageGenerateParams\Quality;
use DedalusSDK\Images\ImageGenerateParams\ResponseFormat;
use DedalusSDK\Images\ImageGenerateParams\Size;
use DedalusSDK\Images\ImageGenerateParams\Style;

/**
 * Generate images from text prompts.
 *
 * Pure image generation models only (DALL-E, GPT Image).
 * For multimodal models like gemini-2.5-flash-image, use /v1/chat/completions.
 *
 * @see DedalusSDK\Services\ImagesService::generate()
 *
 * @phpstan-type ImageGenerateParamsShape = array{
 *   prompt: string,
 *   background?: null|Background|value-of<Background>,
 *   model?: string|null,
 *   moderation?: null|Moderation|value-of<Moderation>,
 *   n?: int|null,
 *   outputCompression?: int|null,
 *   outputFormat?: null|OutputFormat|value-of<OutputFormat>,
 *   partialImages?: int|null,
 *   quality?: null|Quality|value-of<Quality>,
 *   responseFormat?: null|ResponseFormat|value-of<ResponseFormat>,
 *   size?: null|Size|value-of<Size>,
 *   stream?: bool|null,
 *   style?: null|Style|value-of<Style>,
 *   user?: string|null,
 * }
 */
final class ImageGenerateParams implements BaseModel
{
    /** @use SdkModel<ImageGenerateParamsShape> */
    use SdkModel;
    use SdkParams;

    /**
     * A text description of the desired image(s). The maximum length is 32000 characters for `gpt-image-1`, 1000 characters for `dall-e-2` and 4000 characters for `dall-e-3`.
     */
    #[Required]
    public string $prompt;

    /**
     * Allows to set transparency for the background of the generated image(s).
     * This parameter is only supported for `gpt-image-1`. Must be one of
     * `transparent`, `opaque` or `auto` (default value). When `auto` is used, the
     * model will automatically determine the best background for the image.
     *
     * If `transparent`, the output format needs to support transparency, so it
     * should be set to either `png` (default value) or `webp`.
     *
     * @var value-of<Background>|null $background
     */
    #[Optional(enum: Background::class, nullable: true)]
    public ?string $background;

    /**
     * The model to use for image generation. One of `openai/dall-e-2`, `openai/dall-e-3`, or `openai/gpt-image-1`. Defaults to `openai/dall-e-2` unless a parameter specific to `gpt-image-1` is used.
     */
    #[Optional(nullable: true)]
    public ?string $model;

    /**
     * Control the content-moderation level for images generated by `gpt-image-1`. Must be either `low` for less restrictive filtering or `auto` (default value).
     *
     * @var value-of<Moderation>|null $moderation
     */
    #[Optional(enum: Moderation::class, nullable: true)]
    public ?string $moderation;

    /**
     * The number of images to generate. Must be between 1 and 10. For `dall-e-3`, only `n=1` is supported.
     */
    #[Optional(nullable: true)]
    public ?int $n;

    /**
     * The compression level (0-100%) for the generated images. This parameter is only supported for `gpt-image-1` with the `webp` or `jpeg` output formats, and defaults to 100.
     */
    #[Optional('output_compression', nullable: true)]
    public ?int $outputCompression;

    /**
     * The format in which the generated images are returned. This parameter is only supported for `gpt-image-1`. Must be one of `png`, `jpeg`, or `webp`.
     *
     * @var value-of<OutputFormat>|null $outputFormat
     */
    #[Optional('output_format', enum: OutputFormat::class, nullable: true)]
    public ?string $outputFormat;

    /**
     * The number of partial images to generate. This parameter is used for
     * streaming responses that return partial images. Value must be between 0 and 3.
     * When set to 0, the response will be a single image sent in one streaming event.
     *
     * Note that the final image may be sent before the full number of partial images
     * are generated if the full image is generated more quickly.
     */
    #[Optional('partial_images', nullable: true)]
    public ?int $partialImages;

    /**
     * The quality of the image that will be generated.
     *
     * - `auto` (default value) will automatically select the best quality for the given model.
     * - `high`, `medium` and `low` are supported for `gpt-image-1`.
     * - `hd` and `standard` are supported for `dall-e-3`.
     * - `standard` is the only option for `dall-e-2`.
     *
     * @var value-of<Quality>|null $quality
     */
    #[Optional(enum: Quality::class, nullable: true)]
    public ?string $quality;

    /**
     * The format in which generated images with `dall-e-2` and `dall-e-3` are returned. Must be one of `url` or `b64_json`. URLs are only valid for 60 minutes after the image has been generated. This parameter isn't supported for `gpt-image-1` which will always return base64-encoded images.
     *
     * @var value-of<ResponseFormat>|null $responseFormat
     */
    #[Optional('response_format', enum: ResponseFormat::class, nullable: true)]
    public ?string $responseFormat;

    /**
     * The size of the generated images. Must be one of `1024x1024`, `1536x1024` (landscape), `1024x1536` (portrait), or `auto` (default value) for `gpt-image-1`, one of `256x256`, `512x512`, or `1024x1024` for `dall-e-2`, and one of `1024x1024`, `1792x1024`, or `1024x1792` for `dall-e-3`.
     *
     * @var value-of<Size>|null $size
     */
    #[Optional(enum: Size::class, nullable: true)]
    public ?string $size;

    /**
     * Generate the image in streaming mode. Defaults to `false`. See the
     * [Image generation guide](https://platform.openai.com/docs/guides/image-generation) for more information.
     * This parameter is only supported for `gpt-image-1`.
     */
    #[Optional(nullable: true)]
    public ?bool $stream;

    /**
     * The style of the generated images. This parameter is only supported for `dall-e-3`. Must be one of `vivid` or `natural`. Vivid causes the model to lean towards generating hyper-real and dramatic images. Natural causes the model to produce more natural, less hyper-real looking images.
     *
     * @var value-of<Style>|null $style
     */
    #[Optional(enum: Style::class, nullable: true)]
    public ?string $style;

    /**
     * A unique identifier representing your end-user, which can help OpenAI to monitor and detect abuse. [Learn more](https://platform.openai.com/docs/guides/safety-best-practices#end-user-ids).
     */
    #[Optional(nullable: true)]
    public ?string $user;

    /**
     * `new ImageGenerateParams()` is missing required properties by the API.
     *
     * To enforce required parameters use
     * ```
     * ImageGenerateParams::with(prompt: ...)
     * ```
     *
     * Otherwise ensure the following setters are called
     *
     * ```
     * (new ImageGenerateParams)->withPrompt(...)
     * ```
     */
    public function __construct()
    {
        $this->initialize();
    }

    /**
     * Construct an instance from the required parameters.
     *
     * You must use named parameters to construct any parameters with a default value.
     *
     * @param Background|value-of<Background>|null $background
     * @param Moderation|value-of<Moderation>|null $moderation
     * @param OutputFormat|value-of<OutputFormat>|null $outputFormat
     * @param Quality|value-of<Quality>|null $quality
     * @param ResponseFormat|value-of<ResponseFormat>|null $responseFormat
     * @param Size|value-of<Size>|null $size
     * @param Style|value-of<Style>|null $style
     */
    public static function with(
        string $prompt,
        Background|string|null $background = null,
        ?string $model = null,
        Moderation|string|null $moderation = null,
        ?int $n = null,
        ?int $outputCompression = null,
        OutputFormat|string|null $outputFormat = null,
        ?int $partialImages = null,
        Quality|string|null $quality = null,
        ResponseFormat|string|null $responseFormat = null,
        Size|string|null $size = null,
        ?bool $stream = null,
        Style|string|null $style = null,
        ?string $user = null,
    ): self {
        $self = new self;

        $self['prompt'] = $prompt;

        null !== $background && $self['background'] = $background;
        null !== $model && $self['model'] = $model;
        null !== $moderation && $self['moderation'] = $moderation;
        null !== $n && $self['n'] = $n;
        null !== $outputCompression && $self['outputCompression'] = $outputCompression;
        null !== $outputFormat && $self['outputFormat'] = $outputFormat;
        null !== $partialImages && $self['partialImages'] = $partialImages;
        null !== $quality && $self['quality'] = $quality;
        null !== $responseFormat && $self['responseFormat'] = $responseFormat;
        null !== $size && $self['size'] = $size;
        null !== $stream && $self['stream'] = $stream;
        null !== $style && $self['style'] = $style;
        null !== $user && $self['user'] = $user;

        return $self;
    }

    /**
     * A text description of the desired image(s). The maximum length is 32000 characters for `gpt-image-1`, 1000 characters for `dall-e-2` and 4000 characters for `dall-e-3`.
     */
    public function withPrompt(string $prompt): self
    {
        $self = clone $this;
        $self['prompt'] = $prompt;

        return $self;
    }

    /**
     * Allows to set transparency for the background of the generated image(s).
     * This parameter is only supported for `gpt-image-1`. Must be one of
     * `transparent`, `opaque` or `auto` (default value). When `auto` is used, the
     * model will automatically determine the best background for the image.
     *
     * If `transparent`, the output format needs to support transparency, so it
     * should be set to either `png` (default value) or `webp`.
     *
     * @param Background|value-of<Background>|null $background
     */
    public function withBackground(Background|string|null $background): self
    {
        $self = clone $this;
        $self['background'] = $background;

        return $self;
    }

    /**
     * The model to use for image generation. One of `openai/dall-e-2`, `openai/dall-e-3`, or `openai/gpt-image-1`. Defaults to `openai/dall-e-2` unless a parameter specific to `gpt-image-1` is used.
     */
    public function withModel(?string $model): self
    {
        $self = clone $this;
        $self['model'] = $model;

        return $self;
    }

    /**
     * Control the content-moderation level for images generated by `gpt-image-1`. Must be either `low` for less restrictive filtering or `auto` (default value).
     *
     * @param Moderation|value-of<Moderation>|null $moderation
     */
    public function withModeration(Moderation|string|null $moderation): self
    {
        $self = clone $this;
        $self['moderation'] = $moderation;

        return $self;
    }

    /**
     * The number of images to generate. Must be between 1 and 10. For `dall-e-3`, only `n=1` is supported.
     */
    public function withN(?int $n): self
    {
        $self = clone $this;
        $self['n'] = $n;

        return $self;
    }

    /**
     * The compression level (0-100%) for the generated images. This parameter is only supported for `gpt-image-1` with the `webp` or `jpeg` output formats, and defaults to 100.
     */
    public function withOutputCompression(?int $outputCompression): self
    {
        $self = clone $this;
        $self['outputCompression'] = $outputCompression;

        return $self;
    }

    /**
     * The format in which the generated images are returned. This parameter is only supported for `gpt-image-1`. Must be one of `png`, `jpeg`, or `webp`.
     *
     * @param OutputFormat|value-of<OutputFormat>|null $outputFormat
     */
    public function withOutputFormat(
        OutputFormat|string|null $outputFormat
    ): self {
        $self = clone $this;
        $self['outputFormat'] = $outputFormat;

        return $self;
    }

    /**
     * The number of partial images to generate. This parameter is used for
     * streaming responses that return partial images. Value must be between 0 and 3.
     * When set to 0, the response will be a single image sent in one streaming event.
     *
     * Note that the final image may be sent before the full number of partial images
     * are generated if the full image is generated more quickly.
     */
    public function withPartialImages(?int $partialImages): self
    {
        $self = clone $this;
        $self['partialImages'] = $partialImages;

        return $self;
    }

    /**
     * The quality of the image that will be generated.
     *
     * - `auto` (default value) will automatically select the best quality for the given model.
     * - `high`, `medium` and `low` are supported for `gpt-image-1`.
     * - `hd` and `standard` are supported for `dall-e-3`.
     * - `standard` is the only option for `dall-e-2`.
     *
     * @param Quality|value-of<Quality>|null $quality
     */
    public function withQuality(Quality|string|null $quality): self
    {
        $self = clone $this;
        $self['quality'] = $quality;

        return $self;
    }

    /**
     * The format in which generated images with `dall-e-2` and `dall-e-3` are returned. Must be one of `url` or `b64_json`. URLs are only valid for 60 minutes after the image has been generated. This parameter isn't supported for `gpt-image-1` which will always return base64-encoded images.
     *
     * @param ResponseFormat|value-of<ResponseFormat>|null $responseFormat
     */
    public function withResponseFormat(
        ResponseFormat|string|null $responseFormat
    ): self {
        $self = clone $this;
        $self['responseFormat'] = $responseFormat;

        return $self;
    }

    /**
     * The size of the generated images. Must be one of `1024x1024`, `1536x1024` (landscape), `1024x1536` (portrait), or `auto` (default value) for `gpt-image-1`, one of `256x256`, `512x512`, or `1024x1024` for `dall-e-2`, and one of `1024x1024`, `1792x1024`, or `1024x1792` for `dall-e-3`.
     *
     * @param Size|value-of<Size>|null $size
     */
    public function withSize(Size|string|null $size): self
    {
        $self = clone $this;
        $self['size'] = $size;

        return $self;
    }

    /**
     * Generate the image in streaming mode. Defaults to `false`. See the
     * [Image generation guide](https://platform.openai.com/docs/guides/image-generation) for more information.
     * This parameter is only supported for `gpt-image-1`.
     */
    public function withStream(?bool $stream): self
    {
        $self = clone $this;
        $self['stream'] = $stream;

        return $self;
    }

    /**
     * The style of the generated images. This parameter is only supported for `dall-e-3`. Must be one of `vivid` or `natural`. Vivid causes the model to lean towards generating hyper-real and dramatic images. Natural causes the model to produce more natural, less hyper-real looking images.
     *
     * @param Style|value-of<Style>|null $style
     */
    public function withStyle(Style|string|null $style): self
    {
        $self = clone $this;
        $self['style'] = $style;

        return $self;
    }

    /**
     * A unique identifier representing your end-user, which can help OpenAI to monitor and detect abuse. [Learn more](https://platform.openai.com/docs/guides/safety-best-practices#end-user-ids).
     */
    public function withUser(?string $user): self
    {
        $self = clone $this;
        $self['user'] = $user;

        return $self;
    }
}
