<?php

declare(strict_types=1);

namespace DedalusSDK\Chat\Completions\ChatCompletionMessageToolCall;

use DedalusSDK\Core\Attributes\Required;
use DedalusSDK\Core\Concerns\SdkModel;
use DedalusSDK\Core\Contracts\BaseModel;

/**
 * The function that the model called.
 *
 * Fields:
 * - name (required): str
 * - arguments (required): str
 *
 * @phpstan-type FunctionShape = array{arguments: string, name: string}
 */
final class Function_ implements BaseModel
{
    /** @use SdkModel<FunctionShape> */
    use SdkModel;

    /**
     * The arguments to call the function with, as generated by the model in JSON format. Note that the model does not always generate valid JSON, and may hallucinate parameters not defined by your function schema. Validate the arguments in your code before calling your function.
     */
    #[Required]
    public string $arguments;

    /**
     * The name of the function to call.
     */
    #[Required]
    public string $name;

    /**
     * `new Function_()` is missing required properties by the API.
     *
     * To enforce required parameters use
     * ```
     * Function_::with(arguments: ..., name: ...)
     * ```
     *
     * Otherwise ensure the following setters are called
     *
     * ```
     * (new Function_)->withArguments(...)->withName(...)
     * ```
     */
    public function __construct()
    {
        $this->initialize();
    }

    /**
     * Construct an instance from the required parameters.
     *
     * You must use named parameters to construct any parameters with a default value.
     */
    public static function with(string $arguments, string $name): self
    {
        $self = new self;

        $self['arguments'] = $arguments;
        $self['name'] = $name;

        return $self;
    }

    /**
     * The arguments to call the function with, as generated by the model in JSON format. Note that the model does not always generate valid JSON, and may hallucinate parameters not defined by your function schema. Validate the arguments in your code before calling your function.
     */
    public function withArguments(string $arguments): self
    {
        $self = clone $this;
        $self['arguments'] = $arguments;

        return $self;
    }

    /**
     * The name of the function to call.
     */
    public function withName(string $name): self
    {
        $self = clone $this;
        $self['name'] = $name;

        return $self;
    }
}
