<?php

declare(strict_types=1);

namespace DedalusSDK\Images\CreateImageRequest;

/**
 * Control the content-moderation level for images generated by `gpt-image-1`. Must be either `low` for less restrictive filtering or `auto` (default value).
 */
enum Moderation: string
{
    case LOW = 'low';

    case AUTO = 'auto';
}
