<?php

declare(strict_types=1);

namespace DedalusSDK\Chat\Completions\ChatCompletionMessage;

use DedalusSDK\Core\Attributes\Required;
use DedalusSDK\Core\Concerns\SdkModel;
use DedalusSDK\Core\Contracts\BaseModel;

/**
 * If the audio output modality is requested, this object contains data
 * about the audio response from the model. [Learn more](/docs/guides/audio).
 *
 * Fields:
 * - id (required): str
 * - expires_at (required): int
 * - data (required): str
 * - transcript (required): str
 *
 * @phpstan-type AudioShape = array{
 *   id: string, data: string, expiresAt: int, transcript: string
 * }
 */
final class Audio implements BaseModel
{
    /** @use SdkModel<AudioShape> */
    use SdkModel;

    /**
     * Unique identifier for this audio response.
     */
    #[Required]
    public string $id;

    /**
     * Base64 encoded audio bytes generated by the model, in the format
     * specified in the request.
     */
    #[Required]
    public string $data;

    /**
     * The Unix timestamp (in seconds) for when this audio response will
     * no longer be accessible on the server for use in multi-turn
     * conversations.
     */
    #[Required('expires_at')]
    public int $expiresAt;

    /**
     * Transcript of the audio generated by the model.
     */
    #[Required]
    public string $transcript;

    /**
     * `new Audio()` is missing required properties by the API.
     *
     * To enforce required parameters use
     * ```
     * Audio::with(id: ..., data: ..., expiresAt: ..., transcript: ...)
     * ```
     *
     * Otherwise ensure the following setters are called
     *
     * ```
     * (new Audio)->withID(...)->withData(...)->withExpiresAt(...)->withTranscript(...)
     * ```
     */
    public function __construct()
    {
        $this->initialize();
    }

    /**
     * Construct an instance from the required parameters.
     *
     * You must use named parameters to construct any parameters with a default value.
     */
    public static function with(
        string $id,
        string $data,
        int $expiresAt,
        string $transcript
    ): self {
        $self = new self;

        $self['id'] = $id;
        $self['data'] = $data;
        $self['expiresAt'] = $expiresAt;
        $self['transcript'] = $transcript;

        return $self;
    }

    /**
     * Unique identifier for this audio response.
     */
    public function withID(string $id): self
    {
        $self = clone $this;
        $self['id'] = $id;

        return $self;
    }

    /**
     * Base64 encoded audio bytes generated by the model, in the format
     * specified in the request.
     */
    public function withData(string $data): self
    {
        $self = clone $this;
        $self['data'] = $data;

        return $self;
    }

    /**
     * The Unix timestamp (in seconds) for when this audio response will
     * no longer be accessible on the server for use in multi-turn
     * conversations.
     */
    public function withExpiresAt(int $expiresAt): self
    {
        $self = clone $this;
        $self['expiresAt'] = $expiresAt;

        return $self;
    }

    /**
     * Transcript of the audio generated by the model.
     */
    public function withTranscript(string $transcript): self
    {
        $self = clone $this;
        $self['transcript'] = $transcript;

        return $self;
    }
}
