<?php

declare(strict_types=1);

namespace DedalusSDK\Chat\Completions;

use DedalusSDK\Chat\Completions\ChatCompletionAssistantMessageParam\Content;
use DedalusSDK\Chat\Completions\ChatCompletionAssistantMessageParam\FunctionCall;
use DedalusSDK\Chat\Completions\ChatCompletionAssistantMessageParam\ToolCall;
use DedalusSDK\Core\Attributes\Optional;
use DedalusSDK\Core\Attributes\Required;
use DedalusSDK\Core\Concerns\SdkModel;
use DedalusSDK\Core\Contracts\BaseModel;

/**
 * Messages sent by the model in response to user messages.
 *
 * Fields:
 * - content (optional): str | Annotated[list[ChatCompletionRequestAssistantMessageContentPart], MinLen(1), ArrayTitle("ChatCompletionRequestAssistantMessageContentArray")] | None
 * - refusal (optional): str | None
 * - role (required): Literal["assistant"]
 * - name (optional): str
 * - audio (optional): Audio | None
 * - tool_calls (optional): ChatCompletionMessageToolCalls
 * - function_call (optional): FunctionCall | None
 *
 * @phpstan-import-type ContentVariants from \DedalusSDK\Chat\Completions\ChatCompletionAssistantMessageParam\Content
 * @phpstan-import-type ToolCallVariants from \DedalusSDK\Chat\Completions\ChatCompletionAssistantMessageParam\ToolCall
 * @phpstan-import-type AudioShape from \DedalusSDK\Chat\Completions\Audio
 * @phpstan-import-type ContentShape from \DedalusSDK\Chat\Completions\ChatCompletionAssistantMessageParam\Content
 * @phpstan-import-type FunctionCallShape from \DedalusSDK\Chat\Completions\ChatCompletionAssistantMessageParam\FunctionCall
 * @phpstan-import-type ToolCallShape from \DedalusSDK\Chat\Completions\ChatCompletionAssistantMessageParam\ToolCall
 *
 * @phpstan-type ChatCompletionAssistantMessageParamShape = array{
 *   role: 'assistant',
 *   audio?: null|Audio|AudioShape,
 *   content?: ContentShape|null,
 *   functionCall?: null|FunctionCall|FunctionCallShape,
 *   name?: string|null,
 *   refusal?: string|null,
 *   toolCalls?: list<ToolCallShape>|null,
 * }
 */
final class ChatCompletionAssistantMessageParam implements BaseModel
{
    /** @use SdkModel<ChatCompletionAssistantMessageParamShape> */
    use SdkModel;

    /**
     * The role of the messages author, in this case `assistant`.
     *
     * @var 'assistant' $role
     */
    #[Required]
    public string $role = 'assistant';

    /**
     * Data about a previous audio response from the model.
     * [Learn more](/docs/guides/audio).
     *
     * Fields:
     * - id (required): str
     */
    #[Optional(nullable: true)]
    public ?Audio $audio;

    /**
     * The contents of the assistant message. Required unless `tool_calls` or `function_call` is specified.
     *
     * @var ContentVariants|null $content
     */
    #[Optional(union: Content::class, nullable: true)]
    public string|array|null $content;

    /**
     * Deprecated and replaced by `tool_calls`. The name and arguments of a function that should be called, as generated by the model.
     *
     * Fields:
     * - arguments (required): str
     * - name (required): str
     */
    #[Optional('function_call', nullable: true)]
    public ?FunctionCall $functionCall;

    /**
     * An optional name for the participant. Provides the model information to differentiate between participants of the same role.
     */
    #[Optional]
    public ?string $name;

    /**
     * The refusal message by the assistant.
     */
    #[Optional(nullable: true)]
    public ?string $refusal;

    /**
     * The tool calls generated by the model, such as function calls.
     *
     * @var list<ToolCallVariants>|null $toolCalls
     */
    #[Optional('tool_calls', list: ToolCall::class)]
    public ?array $toolCalls;

    public function __construct()
    {
        $this->initialize();
    }

    /**
     * Construct an instance from the required parameters.
     *
     * You must use named parameters to construct any parameters with a default value.
     *
     * @param Audio|AudioShape|null $audio
     * @param ContentShape|null $content
     * @param FunctionCall|FunctionCallShape|null $functionCall
     * @param list<ToolCallShape>|null $toolCalls
     */
    public static function with(
        Audio|array|null $audio = null,
        string|array|null $content = null,
        FunctionCall|array|null $functionCall = null,
        ?string $name = null,
        ?string $refusal = null,
        ?array $toolCalls = null,
    ): self {
        $self = new self;

        null !== $audio && $self['audio'] = $audio;
        null !== $content && $self['content'] = $content;
        null !== $functionCall && $self['functionCall'] = $functionCall;
        null !== $name && $self['name'] = $name;
        null !== $refusal && $self['refusal'] = $refusal;
        null !== $toolCalls && $self['toolCalls'] = $toolCalls;

        return $self;
    }

    /**
     * The role of the messages author, in this case `assistant`.
     *
     * @param 'assistant' $role
     */
    public function withRole(string $role): self
    {
        $self = clone $this;
        $self['role'] = $role;

        return $self;
    }

    /**
     * Data about a previous audio response from the model.
     * [Learn more](/docs/guides/audio).
     *
     * Fields:
     * - id (required): str
     *
     * @param Audio|AudioShape|null $audio
     */
    public function withAudio(Audio|array|null $audio): self
    {
        $self = clone $this;
        $self['audio'] = $audio;

        return $self;
    }

    /**
     * The contents of the assistant message. Required unless `tool_calls` or `function_call` is specified.
     *
     * @param ContentShape|null $content
     */
    public function withContent(string|array|null $content): self
    {
        $self = clone $this;
        $self['content'] = $content;

        return $self;
    }

    /**
     * Deprecated and replaced by `tool_calls`. The name and arguments of a function that should be called, as generated by the model.
     *
     * Fields:
     * - arguments (required): str
     * - name (required): str
     *
     * @param FunctionCall|FunctionCallShape|null $functionCall
     */
    public function withFunctionCall(
        FunctionCall|array|null $functionCall
    ): self {
        $self = clone $this;
        $self['functionCall'] = $functionCall;

        return $self;
    }

    /**
     * An optional name for the participant. Provides the model information to differentiate between participants of the same role.
     */
    public function withName(string $name): self
    {
        $self = clone $this;
        $self['name'] = $name;

        return $self;
    }

    /**
     * The refusal message by the assistant.
     */
    public function withRefusal(?string $refusal): self
    {
        $self = clone $this;
        $self['refusal'] = $refusal;

        return $self;
    }

    /**
     * The tool calls generated by the model, such as function calls.
     *
     * @param list<ToolCallShape> $toolCalls
     */
    public function withToolCalls(array $toolCalls): self
    {
        $self = clone $this;
        $self['toolCalls'] = $toolCalls;

        return $self;
    }
}
