<?php

declare(strict_types=1);

namespace DedalusSDK\Chat\Completions;

use DedalusSDK\Chat\Completions\ChatCompletionMessage\Annotation;
use DedalusSDK\Chat\Completions\ChatCompletionMessage\Audio;
use DedalusSDK\Chat\Completions\ChatCompletionMessage\FunctionCall;
use DedalusSDK\Chat\Completions\ChatCompletionMessage\ToolCall;
use DedalusSDK\Core\Attributes\Optional;
use DedalusSDK\Core\Attributes\Required;
use DedalusSDK\Core\Concerns\SdkModel;
use DedalusSDK\Core\Contracts\BaseModel;

/**
 * A chat completion message generated by the model.
 *
 * Fields:
 * - content (required): str | None
 * - refusal (required): str | None
 * - tool_calls (optional): ChatCompletionMessageToolCalls
 * - annotations (optional): list[AnnotationsItem]
 * - role (required): Literal["assistant"]
 * - function_call (optional): ChatCompletionResponseMessageFunctionCall
 * - audio (optional): ChatCompletionResponseMessageAudio | None
 *
 * @phpstan-import-type ToolCallVariants from \DedalusSDK\Chat\Completions\ChatCompletionMessage\ToolCall
 * @phpstan-import-type AnnotationShape from \DedalusSDK\Chat\Completions\ChatCompletionMessage\Annotation
 * @phpstan-import-type AudioShape from \DedalusSDK\Chat\Completions\ChatCompletionMessage\Audio
 * @phpstan-import-type FunctionCallShape from \DedalusSDK\Chat\Completions\ChatCompletionMessage\FunctionCall
 * @phpstan-import-type ToolCallShape from \DedalusSDK\Chat\Completions\ChatCompletionMessage\ToolCall
 *
 * @phpstan-type ChatCompletionMessageShape = array{
 *   content: string|null,
 *   refusal: string|null,
 *   role: 'assistant',
 *   annotations?: list<Annotation|AnnotationShape>|null,
 *   audio?: null|\DedalusSDK\Chat\Completions\ChatCompletionMessage\Audio|AudioShape,
 *   functionCall?: null|FunctionCall|FunctionCallShape,
 *   toolCalls?: list<ToolCallShape>|null,
 * }
 */
final class ChatCompletionMessage implements BaseModel
{
    /** @use SdkModel<ChatCompletionMessageShape> */
    use SdkModel;

    /**
     * The role of the author of this message.
     *
     * @var 'assistant' $role
     */
    #[Required]
    public string $role = 'assistant';

    /**
     * The contents of the message.
     */
    #[Required]
    public ?string $content;

    /**
     * The refusal message generated by the model.
     */
    #[Required]
    public ?string $refusal;

    /**
     * Annotations for the message, when applicable, as when using the
     * [web search tool](/docs/guides/tools-web-search?api-mode=chat).
     *
     * @var list<Annotation>|null $annotations
     */
    #[Optional(list: Annotation::class)]
    public ?array $annotations;

    /**
     * If the audio output modality is requested, this object contains data
     * about the audio response from the model. [Learn more](/docs/guides/audio).
     *
     * Fields:
     * - id (required): str
     * - expires_at (required): int
     * - data (required): str
     * - transcript (required): str
     */
    #[Optional(nullable: true)]
    public ?Audio $audio;

    /**
     * Deprecated and replaced by `tool_calls`. The name and arguments of a function that should be called, as generated by the model.
     *
     * Fields:
     * - arguments (required): str
     * - name (required): str
     */
    #[Optional('function_call')]
    public ?FunctionCall $functionCall;

    /**
     * The tool calls generated by the model, such as function calls.
     *
     * @var list<ToolCallVariants>|null $toolCalls
     */
    #[Optional('tool_calls', list: ToolCall::class)]
    public ?array $toolCalls;

    /**
     * `new ChatCompletionMessage()` is missing required properties by the API.
     *
     * To enforce required parameters use
     * ```
     * ChatCompletionMessage::with(content: ..., refusal: ...)
     * ```
     *
     * Otherwise ensure the following setters are called
     *
     * ```
     * (new ChatCompletionMessage)->withContent(...)->withRefusal(...)
     * ```
     */
    public function __construct()
    {
        $this->initialize();
    }

    /**
     * Construct an instance from the required parameters.
     *
     * You must use named parameters to construct any parameters with a default value.
     *
     * @param list<Annotation|AnnotationShape>|null $annotations
     * @param Audio|AudioShape|null $audio
     * @param FunctionCall|FunctionCallShape|null $functionCall
     * @param list<ToolCallShape>|null $toolCalls
     */
    public static function with(
        ?string $content,
        ?string $refusal,
        ?array $annotations = null,
        Audio|array|null $audio = null,
        FunctionCall|array|null $functionCall = null,
        ?array $toolCalls = null,
    ): self {
        $self = new self;

        $self['content'] = $content;
        $self['refusal'] = $refusal;

        null !== $annotations && $self['annotations'] = $annotations;
        null !== $audio && $self['audio'] = $audio;
        null !== $functionCall && $self['functionCall'] = $functionCall;
        null !== $toolCalls && $self['toolCalls'] = $toolCalls;

        return $self;
    }

    /**
     * The contents of the message.
     */
    public function withContent(?string $content): self
    {
        $self = clone $this;
        $self['content'] = $content;

        return $self;
    }

    /**
     * The refusal message generated by the model.
     */
    public function withRefusal(?string $refusal): self
    {
        $self = clone $this;
        $self['refusal'] = $refusal;

        return $self;
    }

    /**
     * The role of the author of this message.
     *
     * @param 'assistant' $role
     */
    public function withRole(string $role): self
    {
        $self = clone $this;
        $self['role'] = $role;

        return $self;
    }

    /**
     * Annotations for the message, when applicable, as when using the
     * [web search tool](/docs/guides/tools-web-search?api-mode=chat).
     *
     * @param list<Annotation|AnnotationShape> $annotations
     */
    public function withAnnotations(array $annotations): self
    {
        $self = clone $this;
        $self['annotations'] = $annotations;

        return $self;
    }

    /**
     * If the audio output modality is requested, this object contains data
     * about the audio response from the model. [Learn more](/docs/guides/audio).
     *
     * Fields:
     * - id (required): str
     * - expires_at (required): int
     * - data (required): str
     * - transcript (required): str
     *
     * @param Audio|AudioShape|null $audio
     */
    public function withAudio(
        Audio|array|null $audio
    ): self {
        $self = clone $this;
        $self['audio'] = $audio;

        return $self;
    }

    /**
     * Deprecated and replaced by `tool_calls`. The name and arguments of a function that should be called, as generated by the model.
     *
     * Fields:
     * - arguments (required): str
     * - name (required): str
     *
     * @param FunctionCall|FunctionCallShape $functionCall
     */
    public function withFunctionCall(FunctionCall|array $functionCall): self
    {
        $self = clone $this;
        $self['functionCall'] = $functionCall;

        return $self;
    }

    /**
     * The tool calls generated by the model, such as function calls.
     *
     * @param list<ToolCallShape> $toolCalls
     */
    public function withToolCalls(array $toolCalls): self
    {
        $self = clone $this;
        $self['toolCalls'] = $toolCalls;

        return $self;
    }
}
