<?php

declare(strict_types=1);

namespace DedalusSDK\Chat\Completions;

use DedalusSDK\Core\Attributes\Required;
use DedalusSDK\Core\Concerns\SdkModel;
use DedalusSDK\Core\Contracts\BaseModel;

/**
 * Schema for ChatCompletionRequestMessageContentPartRefusal.
 *
 * Fields:
 * - type (required): Literal["refusal"]
 * - refusal (required): str
 *
 * @phpstan-type ChatCompletionContentPartRefusalParamShape = array{
 *   refusal: string, type: 'refusal'
 * }
 */
final class ChatCompletionContentPartRefusalParam implements BaseModel
{
    /** @use SdkModel<ChatCompletionContentPartRefusalParamShape> */
    use SdkModel;

    /**
     * The type of the content part.
     *
     * @var 'refusal' $type
     */
    #[Required]
    public string $type = 'refusal';

    /**
     * The refusal message generated by the model.
     */
    #[Required]
    public string $refusal;

    /**
     * `new ChatCompletionContentPartRefusalParam()` is missing required properties by the API.
     *
     * To enforce required parameters use
     * ```
     * ChatCompletionContentPartRefusalParam::with(refusal: ...)
     * ```
     *
     * Otherwise ensure the following setters are called
     *
     * ```
     * (new ChatCompletionContentPartRefusalParam)->withRefusal(...)
     * ```
     */
    public function __construct()
    {
        $this->initialize();
    }

    /**
     * Construct an instance from the required parameters.
     *
     * You must use named parameters to construct any parameters with a default value.
     */
    public static function with(string $refusal): self
    {
        $self = new self;

        $self['refusal'] = $refusal;

        return $self;
    }

    /**
     * The refusal message generated by the model.
     */
    public function withRefusal(string $refusal): self
    {
        $self = clone $this;
        $self['refusal'] = $refusal;

        return $self;
    }

    /**
     * The type of the content part.
     *
     * @param 'refusal' $type
     */
    public function withType(string $type): self
    {
        $self = clone $this;
        $self['type'] = $type;

        return $self;
    }
}
