<?php

declare(strict_types=1);

namespace DedalusSDK\Chat\Completions;

use DedalusSDK\Chat\Completions\ChoiceDelta\FunctionCall;
use DedalusSDK\Chat\Completions\ChoiceDelta\Role;
use DedalusSDK\Core\Attributes\Optional;
use DedalusSDK\Core\Concerns\SdkModel;
use DedalusSDK\Core\Contracts\BaseModel;

/**
 * A chat completion delta generated by streamed model responses.
 *
 * Fields:
 * - content (optional): str | None
 * - function_call (optional): ChatCompletionStreamResponseDeltaFunctionCall
 * - tool_calls (optional): list[ChatCompletionMessageToolCallChunk]
 * - role (optional): Literal["developer", "system", "user", "assistant", "tool"]
 * - refusal (optional): str | None
 *
 * @phpstan-import-type FunctionCallShape from \DedalusSDK\Chat\Completions\ChoiceDelta\FunctionCall
 * @phpstan-import-type ChoiceDeltaToolCallShape from \DedalusSDK\Chat\Completions\ChoiceDeltaToolCall
 *
 * @phpstan-type ChoiceDeltaShape = array{
 *   content?: string|null,
 *   functionCall?: null|FunctionCall|FunctionCallShape,
 *   refusal?: string|null,
 *   role?: null|Role|value-of<Role>,
 *   toolCalls?: list<ChoiceDeltaToolCall|ChoiceDeltaToolCallShape>|null,
 * }
 */
final class ChoiceDelta implements BaseModel
{
    /** @use SdkModel<ChoiceDeltaShape> */
    use SdkModel;

    /**
     * The contents of the chunk message.
     */
    #[Optional(nullable: true)]
    public ?string $content;

    /**
     * Deprecated and replaced by `tool_calls`. The name and arguments of a function that should be called, as generated by the model.
     *
     * Fields:
     * - arguments (optional): str
     * - name (optional): str
     */
    #[Optional('function_call')]
    public ?FunctionCall $functionCall;

    /**
     * The refusal message generated by the model.
     */
    #[Optional(nullable: true)]
    public ?string $refusal;

    /**
     * The role of the author of this message.
     *
     * @var value-of<Role>|null $role
     */
    #[Optional(enum: Role::class)]
    public ?string $role;

    /** @var list<ChoiceDeltaToolCall>|null $toolCalls */
    #[Optional('tool_calls', list: ChoiceDeltaToolCall::class)]
    public ?array $toolCalls;

    public function __construct()
    {
        $this->initialize();
    }

    /**
     * Construct an instance from the required parameters.
     *
     * You must use named parameters to construct any parameters with a default value.
     *
     * @param FunctionCall|FunctionCallShape|null $functionCall
     * @param Role|value-of<Role>|null $role
     * @param list<ChoiceDeltaToolCall|ChoiceDeltaToolCallShape>|null $toolCalls
     */
    public static function with(
        ?string $content = null,
        FunctionCall|array|null $functionCall = null,
        ?string $refusal = null,
        Role|string|null $role = null,
        ?array $toolCalls = null,
    ): self {
        $self = new self;

        null !== $content && $self['content'] = $content;
        null !== $functionCall && $self['functionCall'] = $functionCall;
        null !== $refusal && $self['refusal'] = $refusal;
        null !== $role && $self['role'] = $role;
        null !== $toolCalls && $self['toolCalls'] = $toolCalls;

        return $self;
    }

    /**
     * The contents of the chunk message.
     */
    public function withContent(?string $content): self
    {
        $self = clone $this;
        $self['content'] = $content;

        return $self;
    }

    /**
     * Deprecated and replaced by `tool_calls`. The name and arguments of a function that should be called, as generated by the model.
     *
     * Fields:
     * - arguments (optional): str
     * - name (optional): str
     *
     * @param FunctionCall|FunctionCallShape $functionCall
     */
    public function withFunctionCall(FunctionCall|array $functionCall): self
    {
        $self = clone $this;
        $self['functionCall'] = $functionCall;

        return $self;
    }

    /**
     * The refusal message generated by the model.
     */
    public function withRefusal(?string $refusal): self
    {
        $self = clone $this;
        $self['refusal'] = $refusal;

        return $self;
    }

    /**
     * The role of the author of this message.
     *
     * @param Role|value-of<Role> $role
     */
    public function withRole(Role|string $role): self
    {
        $self = clone $this;
        $self['role'] = $role;

        return $self;
    }

    /**
     * @param list<ChoiceDeltaToolCall|ChoiceDeltaToolCallShape> $toolCalls
     */
    public function withToolCalls(array $toolCalls): self
    {
        $self = clone $this;
        $self['toolCalls'] = $toolCalls;

        return $self;
    }
}
