<?php

declare(strict_types=1);

namespace DedalusSDK\Chat\Completions;

use DedalusSDK\Chat\Completions\Choice\FinishReason;
use DedalusSDK\Core\Attributes\Optional;
use DedalusSDK\Core\Attributes\Required;
use DedalusSDK\Core\Concerns\SdkModel;
use DedalusSDK\Core\Contracts\BaseModel;

/**
 * A chat completion choice.
 *
 * OpenAI-compatible choice object for non-streaming responses.
 * Part of the ChatCompletion response.
 *
 * @phpstan-import-type ChatCompletionMessageShape from \DedalusSDK\Chat\Completions\ChatCompletionMessage
 * @phpstan-import-type ChoiceLogprobsShape from \DedalusSDK\Chat\Completions\ChoiceLogprobs
 *
 * @phpstan-type ChoiceShape = array{
 *   index: int,
 *   message: ChatCompletionMessage|ChatCompletionMessageShape,
 *   finishReason?: null|FinishReason|value-of<FinishReason>,
 *   logprobs?: null|ChoiceLogprobs|ChoiceLogprobsShape,
 * }
 */
final class Choice implements BaseModel
{
    /** @use SdkModel<ChoiceShape> */
    use SdkModel;

    /**
     * The index of the choice in the list of choices.
     */
    #[Required]
    public int $index;

    /**
     * A chat completion message generated by the model.
     */
    #[Required]
    public ChatCompletionMessage $message;

    /**
     * The reason the model stopped generating tokens. This will be `stop` if the model hit a natural stop point or a provided stop sequence,
     * `length` if the maximum number of tokens specified in the request was reached,
     * `content_filter` if content was omitted due to a flag from our content filters,
     * `tool_calls` if the model called a tool, or `function_call` (deprecated) if the model called a function.
     *
     * @var value-of<FinishReason>|null $finishReason
     */
    #[Optional('finish_reason', enum: FinishReason::class, nullable: true)]
    public ?string $finishReason;

    /**
     * Log probability information for the choice.
     */
    #[Optional(nullable: true)]
    public ?ChoiceLogprobs $logprobs;

    /**
     * `new Choice()` is missing required properties by the API.
     *
     * To enforce required parameters use
     * ```
     * Choice::with(index: ..., message: ...)
     * ```
     *
     * Otherwise ensure the following setters are called
     *
     * ```
     * (new Choice)->withIndex(...)->withMessage(...)
     * ```
     */
    public function __construct()
    {
        $this->initialize();
    }

    /**
     * Construct an instance from the required parameters.
     *
     * You must use named parameters to construct any parameters with a default value.
     *
     * @param ChatCompletionMessage|ChatCompletionMessageShape $message
     * @param FinishReason|value-of<FinishReason>|null $finishReason
     * @param ChoiceLogprobs|ChoiceLogprobsShape|null $logprobs
     */
    public static function with(
        int $index,
        ChatCompletionMessage|array $message,
        FinishReason|string|null $finishReason = null,
        ChoiceLogprobs|array|null $logprobs = null,
    ): self {
        $self = new self;

        $self['index'] = $index;
        $self['message'] = $message;

        null !== $finishReason && $self['finishReason'] = $finishReason;
        null !== $logprobs && $self['logprobs'] = $logprobs;

        return $self;
    }

    /**
     * The index of the choice in the list of choices.
     */
    public function withIndex(int $index): self
    {
        $self = clone $this;
        $self['index'] = $index;

        return $self;
    }

    /**
     * A chat completion message generated by the model.
     *
     * @param ChatCompletionMessage|ChatCompletionMessageShape $message
     */
    public function withMessage(ChatCompletionMessage|array $message): self
    {
        $self = clone $this;
        $self['message'] = $message;

        return $self;
    }

    /**
     * The reason the model stopped generating tokens. This will be `stop` if the model hit a natural stop point or a provided stop sequence,
     * `length` if the maximum number of tokens specified in the request was reached,
     * `content_filter` if content was omitted due to a flag from our content filters,
     * `tool_calls` if the model called a tool, or `function_call` (deprecated) if the model called a function.
     *
     * @param FinishReason|value-of<FinishReason>|null $finishReason
     */
    public function withFinishReason(
        FinishReason|string|null $finishReason
    ): self {
        $self = clone $this;
        $self['finishReason'] = $finishReason;

        return $self;
    }

    /**
     * Log probability information for the choice.
     *
     * @param ChoiceLogprobs|ChoiceLogprobsShape|null $logprobs
     */
    public function withLogprobs(ChoiceLogprobs|array|null $logprobs): self
    {
        $self = clone $this;
        $self['logprobs'] = $logprobs;

        return $self;
    }
}
