<?php

declare(strict_types=1);

namespace DedalusSDK\Chat\Completions;

use DedalusSDK\Core\Attributes\Optional;
use DedalusSDK\Core\Concerns\SdkModel;
use DedalusSDK\Core\Contracts\BaseModel;

/**
 * Breakdown of tokens used in a completion.
 *
 * Fields:
 * - accepted_prediction_tokens (optional): int
 * - audio_tokens (optional): int
 * - reasoning_tokens (optional): int
 * - rejected_prediction_tokens (optional): int
 *
 * @phpstan-type CompletionTokensDetailsShape = array{
 *   acceptedPredictionTokens?: int|null,
 *   audioTokens?: int|null,
 *   reasoningTokens?: int|null,
 *   rejectedPredictionTokens?: int|null,
 * }
 */
final class CompletionTokensDetails implements BaseModel
{
    /** @use SdkModel<CompletionTokensDetailsShape> */
    use SdkModel;

    /**
     * When using Predicted Outputs, the number of tokens in the
     * prediction that appeared in the completion.
     */
    #[Optional('accepted_prediction_tokens')]
    public ?int $acceptedPredictionTokens;

    /**
     * Audio input tokens generated by the model.
     */
    #[Optional('audio_tokens')]
    public ?int $audioTokens;

    /**
     * Tokens generated by the model for reasoning.
     */
    #[Optional('reasoning_tokens')]
    public ?int $reasoningTokens;

    /**
     * When using Predicted Outputs, the number of tokens in the
     * prediction that did not appear in the completion. However, like
     * reasoning tokens, these tokens are still counted in the total
     * completion tokens for purposes of billing, output, and context window
     * limits.
     */
    #[Optional('rejected_prediction_tokens')]
    public ?int $rejectedPredictionTokens;

    public function __construct()
    {
        $this->initialize();
    }

    /**
     * Construct an instance from the required parameters.
     *
     * You must use named parameters to construct any parameters with a default value.
     */
    public static function with(
        ?int $acceptedPredictionTokens = null,
        ?int $audioTokens = null,
        ?int $reasoningTokens = null,
        ?int $rejectedPredictionTokens = null,
    ): self {
        $self = new self;

        null !== $acceptedPredictionTokens && $self['acceptedPredictionTokens'] = $acceptedPredictionTokens;
        null !== $audioTokens && $self['audioTokens'] = $audioTokens;
        null !== $reasoningTokens && $self['reasoningTokens'] = $reasoningTokens;
        null !== $rejectedPredictionTokens && $self['rejectedPredictionTokens'] = $rejectedPredictionTokens;

        return $self;
    }

    /**
     * When using Predicted Outputs, the number of tokens in the
     * prediction that appeared in the completion.
     */
    public function withAcceptedPredictionTokens(
        int $acceptedPredictionTokens
    ): self {
        $self = clone $this;
        $self['acceptedPredictionTokens'] = $acceptedPredictionTokens;

        return $self;
    }

    /**
     * Audio input tokens generated by the model.
     */
    public function withAudioTokens(int $audioTokens): self
    {
        $self = clone $this;
        $self['audioTokens'] = $audioTokens;

        return $self;
    }

    /**
     * Tokens generated by the model for reasoning.
     */
    public function withReasoningTokens(int $reasoningTokens): self
    {
        $self = clone $this;
        $self['reasoningTokens'] = $reasoningTokens;

        return $self;
    }

    /**
     * When using Predicted Outputs, the number of tokens in the
     * prediction that did not appear in the completion. However, like
     * reasoning tokens, these tokens are still counted in the total
     * completion tokens for purposes of billing, output, and context window
     * limits.
     */
    public function withRejectedPredictionTokens(
        int $rejectedPredictionTokens
    ): self {
        $self = clone $this;
        $self['rejectedPredictionTokens'] = $rejectedPredictionTokens;

        return $self;
    }
}
