<?php

declare(strict_types=1);

namespace DedalusSDK\Chat\Completions;

use DedalusSDK\Chat\Completions\StreamChoice\FinishReason;
use DedalusSDK\Core\Attributes\Optional;
use DedalusSDK\Core\Attributes\Required;
use DedalusSDK\Core\Concerns\SdkModel;
use DedalusSDK\Core\Contracts\BaseModel;

/**
 * Schema for ChatCompletionStreamResponseChoicesItem.
 *
 * Fields:
 * - delta (required): ChatCompletionStreamResponseDelta
 * - logprobs (optional): ChatCompletionStreamResponseChoicesItemLogprobs
 * - finish_reason (required): Literal["stop", "length", "tool_calls", "content_filter", "function_call"]
 * - index (required): int
 *
 * @phpstan-import-type ChoiceDeltaShape from \DedalusSDK\Chat\Completions\ChoiceDelta
 * @phpstan-import-type StreamChoiceLogprobsShape from \DedalusSDK\Chat\Completions\StreamChoiceLogprobs
 *
 * @phpstan-type StreamChoiceShape = array{
 *   delta: ChoiceDelta|ChoiceDeltaShape,
 *   finishReason: null|FinishReason|value-of<FinishReason>,
 *   index: int,
 *   logprobs?: null|StreamChoiceLogprobs|StreamChoiceLogprobsShape,
 * }
 */
final class StreamChoice implements BaseModel
{
    /** @use SdkModel<StreamChoiceShape> */
    use SdkModel;

    /**
     * A chat completion delta generated by streamed model responses.
     */
    #[Required]
    public ChoiceDelta $delta;

    /**
     * The reason the model stopped generating tokens. This will be `stop` if the model hit a natural stop point or a provided stop sequence,
     * `length` if the maximum number of tokens specified in the request was reached,
     * `content_filter` if content was omitted due to a flag from our content filters,
     * `tool_calls` if the model called a tool, or `function_call` (deprecated) if the model called a function.
     *
     * @var value-of<FinishReason>|null $finishReason
     */
    #[Required('finish_reason', enum: FinishReason::class)]
    public ?string $finishReason;

    /**
     * The index of the choice in the list of choices.
     */
    #[Required]
    public int $index;

    /**
     * Log probability information for the choice.
     *
     * Fields:
     * - content (required): list[ChatCompletionTokenLogprob]
     * - refusal (required): list[ChatCompletionTokenLogprob]
     */
    #[Optional(nullable: true)]
    public ?StreamChoiceLogprobs $logprobs;

    /**
     * `new StreamChoice()` is missing required properties by the API.
     *
     * To enforce required parameters use
     * ```
     * StreamChoice::with(delta: ..., finishReason: ..., index: ...)
     * ```
     *
     * Otherwise ensure the following setters are called
     *
     * ```
     * (new StreamChoice)->withDelta(...)->withFinishReason(...)->withIndex(...)
     * ```
     */
    public function __construct()
    {
        $this->initialize();
    }

    /**
     * Construct an instance from the required parameters.
     *
     * You must use named parameters to construct any parameters with a default value.
     *
     * @param ChoiceDelta|ChoiceDeltaShape $delta
     * @param FinishReason|value-of<FinishReason>|null $finishReason
     * @param StreamChoiceLogprobs|StreamChoiceLogprobsShape|null $logprobs
     */
    public static function with(
        ChoiceDelta|array $delta,
        FinishReason|string|null $finishReason,
        int $index,
        StreamChoiceLogprobs|array|null $logprobs = null,
    ): self {
        $self = new self;

        $self['delta'] = $delta;
        $self['finishReason'] = $finishReason;
        $self['index'] = $index;

        null !== $logprobs && $self['logprobs'] = $logprobs;

        return $self;
    }

    /**
     * A chat completion delta generated by streamed model responses.
     *
     * @param ChoiceDelta|ChoiceDeltaShape $delta
     */
    public function withDelta(ChoiceDelta|array $delta): self
    {
        $self = clone $this;
        $self['delta'] = $delta;

        return $self;
    }

    /**
     * The reason the model stopped generating tokens. This will be `stop` if the model hit a natural stop point or a provided stop sequence,
     * `length` if the maximum number of tokens specified in the request was reached,
     * `content_filter` if content was omitted due to a flag from our content filters,
     * `tool_calls` if the model called a tool, or `function_call` (deprecated) if the model called a function.
     *
     * @param FinishReason|value-of<FinishReason>|null $finishReason
     */
    public function withFinishReason(
        FinishReason|string|null $finishReason
    ): self {
        $self = clone $this;
        $self['finishReason'] = $finishReason;

        return $self;
    }

    /**
     * The index of the choice in the list of choices.
     */
    public function withIndex(int $index): self
    {
        $self = clone $this;
        $self['index'] = $index;

        return $self;
    }

    /**
     * Log probability information for the choice.
     *
     * Fields:
     * - content (required): list[ChatCompletionTokenLogprob]
     * - refusal (required): list[ChatCompletionTokenLogprob]
     *
     * @param StreamChoiceLogprobs|StreamChoiceLogprobsShape|null $logprobs
     */
    public function withLogprobs(
        StreamChoiceLogprobs|array|null $logprobs
    ): self {
        $self = clone $this;
        $self['logprobs'] = $logprobs;

        return $self;
    }
}
